spring:
  application:
    name: config-server
  config:
    activate:
      on-profile: localhost
info:
  component: Config Server

---

spring:
  profiles:
    active: localhost
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mtaltn/stock-management-configs.git
          label: main

logging:
  level:
    root: debug
server:
  port: 8888

---
spring:
  profiles:
    active: stage
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mtaltn/stock-management-configs.git
          label: main

logging:
  level:
    root: debug
server:
  port: 8888
